repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: v0.15.6
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format
- repo: https://github.com/allganize/ty-pre-commit
  rev: v0.0.23
  hooks:
    - id: ty-check
      additional_dependencies: ["types-aiofiles",
                                "types-frozendict",
                                "types-emoji",
                                "types-python-dateutil",
                                "types-redis",
                                "pydantic",
                                "quart",
                                "pytest",
                                "pytest_httpserver",
                                "fakeredis"]
