[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "fxtumblr"
version = "2.0.0"
description = "Tumblr embed wrapper"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
	"aiofiles",
	"httpx",
	"redis",
	"frozendict",
	"emoji",
	"python-dateutil",
	"nh3",
	"markupsafe",
	"pydantic",
]

[project.optional-dependencies]
embed-server = [
	"Quart",
]
render-playwright = [
	"playwright",
	"jinja2",
]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "ASYNC", "A", "B", "D", "F", "S", "I", "W"]
ignore = ["D212", "D203", "D205", "D202", "ASYNC109", "S101"]

[dependency-groups]
test = [
    "pytest",
	"pytest-asyncio",
	"pytest-dotenv",
    "pytest-httpserver",
    "pytest-cov",
    "fakeredis",
]
typing = [
    "mypy",
    "types-frozendict",
    "types-emoji",
	"types-python-dateutil",
    "types-redis",
    "types-aiofiles",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"

[tool.mypy]
exclude = ["tests"]
check_untyped_defs = true

[tool.setuptools]
packages = ["fxtumblr", "fxtumblr_render"]
